apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.kubeshark.com
    chart: kubeshark
    targetRevision: 41.3.0

    helm:
      valuesObject:

        enterprise:
          enabled: false

        # ðŸ”¥ important fixes
        rbac:
          create: true

        serviceAccount:
          create: true
          name: kubeshark-service-account

        workers:
          enabled: false

        tap:
          enabled: false

        frontend:
          service:
            type: ClusterIP

        persistentStorage: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

