apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default
  source:
    chart: kubeshark
    repoURL: https://helm.kubeshark.com
    targetRevision: 52.11.0
    helm:
      valuesObject:
        tap:
          hostNetwork: false
          metrics:
            port: 19100
          resources:
            requests:
              cpu: 50m        # Reduce from 100m to 50m
              memory: 50Mi
            limits:
              cpu: 750m
              memory: 5Gi
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi
        frontend:
          service:
            type: ClusterIP
        persistentStorage: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
