apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.kubeshark.com
    chart: kubeshark
    targetRevision: 41.3.0
    helm:
      valuesObject:
        enterprise:
          enabled: false
        
        serviceAccount:
          create: true
          name: kubeshark-service-account
        
        frontend:
          service:
            type: ClusterIP
        
        persistentStorage: false
        
        # Add environment variables for the hub pod
        tap:
          resources:
            limits:
              memory: 1Gi
              cpu: 750m
            requests:
              memory: 512Mi
              cpu: 250m
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
