apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.kubeshark.com
    chart: kubeshark
    targetRevision: 52.11.0

    helm:
      valuesObject:

        # ðŸ”´ Disable Enterprise (No License Needed)
        enterprise:
          enabled: false

        # Frontend Service
        frontend:
          service:
            type: ClusterIP

        # Disable Persistent Storage (Optional)
        persistentStorage: false

        # Hub Resources
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi

        # Tap (Traffic Capture) Settings
        tap:
          hostNetwork: false

          metrics:
            port: 19100

          resources:
            limits:
              cpu: 750m
              memory: 5Gi
            requests:
              cpu: 50m
              memory: 50Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
