apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ghcr.io/kubeshark/helm
    chart: kubeshark
    targetRevision: 52.2.5
    helm:
      parameters:
        - name: tap.enabled
          value: "true"
        - name: cloud.enabled
          value: "false"

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

