apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default
  source:
    chart: kubeshark
    repoURL: https://helm.kubeshark.com
    targetRevision: 52.3.78
    helm:
      valuesObject:
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi
        frontend:
          service:
            type: ClusterIP
        persistentStorage: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
