apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/habdelazim743-collab/complete_k8s_config_for_netfix_app.git # Same repo
    targetRevision: main
    path: kubeshark  # Points to the kubeshark directory
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
