apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
spec:
  project: default
  source:
    chart: kubeshark
    repoURL: https://helm.kubeshark.com
    targetRevision: 52.3.78
    helm:
      valuesObject:
        tap:
          docker:
            registry: docker.io/kubeshark
            tag: 52.3.78
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 50Mi
        frontend:
          service:
            type: ClusterIP
         env:
           REACT_APP_DISSECTORS_UPDATING_ENABLED: "true"
        persistentStorage: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
