apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: netfix-root
spec:
  project: default

  source:
    repoURL: https://helm.kubeshark.co
    chart: kubeshark
    targetRevision: "*"
    helm:
      valueFiles:
        - kubeshark/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

