apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates

  sources:
    # values Repo
    - repoURL: https://github.com/habdelazim743-collab/complete_k8s_config_for_netfix_app
      targetRevision: main
      ref: values
      path: logging

    # Elasticsearch
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 7.17.3
      helm:
        valueFiles:
          - $values/logging/elasticsearch-values.yaml

    # Kibana
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 7.17.3
      helm:
        valueFiles:
          - $values/logging/kibana-values.yaml

    # Filebeat
    - repoURL: https://helm.elastic.co
      chart: filebeat
      targetRevision: 7.17.3
      helm:
        valueFiles:
          - $values/logging/filebeat-values.yaml
  
