apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netfix-ingress
  namespace: auth
  annotations:
    kubernetes.io/ingress.class: alb

    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # HTTP فقط دلوقتي
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

    # Healthcheck مناسب لـ Keycloak
    alb.ingress.kubernetes.io/healthcheck-path: /health/ready
    alb.ingress.kubernetes.io/healthcheck-port: "9000"
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"

spec:
  ingressClassName: alb
  rules:
    # ===== Main App (oauth2-proxy) =====
    - host: netfix.habdelazim.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80

    # ===== Keycloak Direct =====
    - host: auth-netfix.habdelazim.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080


