apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        args:
          - --http-address=0.0.0.0:4180
          - --provider=oidc
          - --scope=openid profile email
          - --oidc-issuer-url=https://auth-netfix.habdelazim.xyz/realms/master
          - --redirect-url=https://netfix.habdelazim.xyz/oauth2/callback
          - --upstream=http://app-service.default.svc.cluster.local:80
          - --email-domain=*
          - --cookie-secure=true
          - --cookie-domain=.habdelazim.xyz
          - --whitelist-domain=.habdelazim.xyz
          - --skip-provider-button
          - --ping-path=/ping
          - --code-challenge-method=S256
          - --pass-host-header=true
          - --skip-auth-regex=^/watch.*$
          - --skip-auth-regex=^/static/.*$
          - --skip-auth-regex=^/media/.*$
          - --skip-auth-regex=.*\.mp4$
          - --skip-auth-regex=.*\.m3u8$
        envFrom:
          - secretRef:
              name: oauth2-proxy-secret
        ports:
          - containerPort: 4180
